/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinaljuego;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Iterator;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.Timer;

/**
 *
 * @author JDevp
 */
public class nivel2 extends javax.swing.JFrame {

    
    static int counter = 0, iteration = 1, fallas = 0;
    
    Multiplicacion mult = new Multiplicacion(); 
    List<Multiplicacion> iteratingList = mult.getIteratingList(); // Almacena las tablas
    
    Componente[][] botones = new Componente[10][10];
    int filas = 10;
    int columnas =10;
    int totalscore = 0;
    //private boolean checkButton = false;
    private final boolean  tiempo;
    private final boolean sonido;
    private  boolean control_score = true;

    /**
     * Creates new form nivel2
     */
    public nivel2(Boolean time, Boolean sound) {
        
        initComponents();
        this.tiempo = time;
        this.sonido = sound;
        
        lblAnimacion.setVisible(false);
        
        dibujarTabla(); // Generar componentes dinamicamente
        
        mult.fill_tabla(9); // 81 respuestas posibles
        
        // Operación inicial: Elemento 0 de la lista.
        lblMultiplicando.setText(String.valueOf(iteratingList.get(0).getMultiplicando()));
        lblMultiplicador.setText(String.valueOf(iteratingList.get(0).getMultiplicador()));
        
         marcar_operacion(iteratingList.get(0).getMultiplicando(),iteratingList.get(0).getMultiplicador());
        
        // Para ir verificando por el terminal las iteraciones
        mostrarLista();
        
        // Mostrar score inicial (0)
        labelScore.setText(String.valueOf(totalscore));
        tiempo();
        check_disabled_boton();

    }
    
    public static int getCounter() {
        return counter;
    }

    public static void setCounter(int counter) {
        nivel1.counter = counter;
    }
    
    public void tiempo(){
        System.out.println(tiempo);
            if (tiempo){
               Tiempo c=new Tiempo(this.lblTiempo); //Intancio la clase
               c.start(); //Ejecuto el metodo run del Thread
            } else {
                System.out.println("Tiempo deshabilitado");
            }

    }
    
    public void mostrarLista(){         
        Iterator<Multiplicacion> itrPartidos = iteratingList.iterator();
        while (itrPartidos.hasNext()) {
            Multiplicacion partido = itrPartidos.next();
            System.out.println(partido.getMultiplicando() + " x " + partido.getMultiplicador() + " = " + partido.getRespuesta());
        }  
        System.out.println("-------------------");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnReiniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelScore = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        lblAnimacion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn5 = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblSigno = new javax.swing.JLabel();
        lblMultiplicando = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        lblMultiplicador = new javax.swing.JLabel();
        lblsigno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nivel 2");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/atras.png"))); // NOI18N
        btnAtras.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 83, 53));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 11, 460, 340));

        jPanel2.setBackground(new java.awt.Color(215, 215, 215));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReiniciar.setBackground(new java.awt.Color(221, 221, 221));
        btnReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cambiar.png"))); // NOI18N
        btnReiniciar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        jPanel2.add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 158, 85, 61));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Multiply");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 1, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nivel 2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 51, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Score:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 111, -1, -1));

        labelScore.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelScore.setText("0");
        jPanel2.add(labelScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 111, 44, -1));

        lblTiempo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(lblTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 100, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 210, 230));
        getContentPane().add(lblAnimacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 200, 170));

        jPanel3.setOpaque(false);

        btn5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btnborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/borrar.png"))); // NOI18N
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btnVerificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVerificar.setText("Check");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, -1, -1));

        jPanel4.setOpaque(false);

        lblSigno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSigno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/igual.png"))); // NOI18N

        lblMultiplicando.setBackground(new java.awt.Color(204, 204, 204));
        lblMultiplicando.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMultiplicando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMultiplicando.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblMultiplicando.setOpaque(true);

        lblResultado.setBackground(new java.awt.Color(204, 204, 204));
        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblResultado.setOpaque(true);

        lblMultiplicador.setBackground(new java.awt.Color(204, 204, 204));
        lblMultiplicador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMultiplicador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMultiplicador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblMultiplicador.setOpaque(true);

        lblsigno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsigno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/multiplicacion.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMultiplicando, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblsigno)
                .addGap(16, 16, 16)
                .addComponent(lblMultiplicador, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMultiplicando, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMultiplicador, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsigno)
                            .addComponent(lblSigno))))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 397, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        counter = 0; 
        iteration = 1;
        this.hide();
        principal prin = new principal();
        prin.show();
        prin.getContentPane().setBackground( new Color(173, 202, 255));
    }//GEN-LAST:event_btnAtrasActionPerformed

    public void dibujarTabla(){
        int count = 0;
        for (int fila = 0; fila < filas; fila++) {
            for (int columna = 0; columna < columnas; columna++) {
                botones[fila][columna] = new Componente(45 * columna, 32 * fila, 55, 45);
                //botones[fila][columna].cambiarNombre(fila,columna);
                jPanel1.add(botones[fila][columna]);
                if (fila == 0 && columna == 0) {
                    botones[fila][columna].setHorizontalAlignment(SwingConstants.CENTER);
                    botones[fila][columna].setX("X");
                } else {
                    //Border border = BorderFactory.createLineBorder(Color.WHITE, 5);

                    //botones[fila][columna].setOpaque(true);
                    if (fila == 0) {
                        //botones[fila][columna].setBackground(Color.red);
                        botones[fila][columna].setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                        botones[fila][columna].setHorizontalAlignment(SwingConstants.CENTER);
                        //botones[fila][columna].setBorder(border);
                        botones[fila][columna].setForeground(Color.white);
                        botones[fila][columna].setFilaInicio(count);
                    }
                    if (columna == 0) {
                        //botones[fila][columna].setBackground(Color.red);
                        botones[fila][columna].setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                        botones[fila][columna].setHorizontalAlignment(SwingConstants.CENTER);
                        //botones[fila][columna].setBorder(border);
                        botones[fila][columna].setForeground(Color.white);
                        botones[fila][columna].setColumnaInicio(fila - 1);
                    }
                    count++;
                }
            }
        }
    }
    
    public void check_enabled_boton(){
            btnVerificar.setEnabled(true);
    }

    public void check_disabled_boton(){
            btnVerificar.setEnabled(false);
    }

    
    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        if (counter==82){
            this.hide();
            resultados fin = new resultados("2", labelScore.getText() , "81", lblTiempo.getText());
            fin.show();
        } else {
        for(int i = counter; i < iteration; i++){

            System.out.println(iteratingList.get(counter).getMultiplicando()+ " x " + iteratingList.get(counter).getMultiplicador() + " = " +iteratingList.get(counter).getRespuesta());
        }
        if (Integer.parseInt(lblResultado.getText()) == iteratingList.get(counter).getRespuesta()) {
            
            diccionario_respuestas(iteratingList.get(counter).getMultiplicando(),iteratingList.get(counter).getMultiplicador(),iteratingList.get(counter).getRespuesta());
            System.out.println("correcto");
            //lblAnimacion.setVisible(true);
            limpiar(); // Resultado
            check_disabled_boton();
            animacion_respuesta_correcta();

            counter++; // Avanzar si la respuesta es correcta
            
            // Marcar fila y columna del multiplicando y multiplicador
            desmarcar_operacion(iteratingList.get(counter-1).getMultiplicando(),iteratingList.get(counter-1).getMultiplicador());
            marcar_operacion(iteratingList.get(counter).getMultiplicando(),iteratingList.get(counter).getMultiplicador());           
            
            if(control_score){
                totalscore++;
            }
            control_score = true;
            lblMultiplicando.setText(String.valueOf(iteratingList.get(counter).getMultiplicando()));
            lblMultiplicador.setText(String.valueOf(iteratingList.get(counter).getMultiplicador()));
        } else {
            System.out.println("incorrecto");
            fallas++;
            control_score = false;
            System.out.println("falla "+fallas);
            animacion_respuesta_incorrecta();
            limpiar(); // Resultado
            check_disabled_boton();
        }

        System.out.println(iteration);
        iteration ++;
        
        labelScore.setText(String.valueOf(totalscore));         
        }        
    }//GEN-LAST:event_btnVerificarActionPerformed
    public void marcar_operacion(int multiplicando, int multiplicador){
            for(int  fila=0; fila<filas; fila++){
            for(int columna=0; columna<columnas; columna++){
                    botones[multiplicando][0].setForeground(Color.yellow);
                    botones[0][multiplicador].setForeground(Color.yellow); 
            }}     
    }

    public void desmarcar_operacion(int multiplicando, int multiplicador){
            for(int  fila=0; fila<filas; fila++){
            for(int columna=0; columna<columnas; columna++){
                    botones[multiplicando][0].setForeground(Color.white);
                    botones[0][multiplicador].setForeground(Color.white); 
            }}     
    }
    public void animacion_respuesta_correcta(){
        
        Icon i = new ImageIcon("feliz.png");
        lblAnimacion.setIcon(i);
        
        Icon signo = new ImageIcon("igual.png");
        lblSigno.setIcon(signo);

        lblAnimacion.setVisible(true);
        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lblAnimacion.setVisible(false);
            }
        });
        timer.start();  
    }

    public void animacion_respuesta_incorrecta(){
        Icon i = new ImageIcon("triste.png");
        lblAnimacion.setIcon(i);
        lblAnimacion.setVisible(true);

        Icon signo = new ImageIcon("desigual.png");
        lblSigno.setIcon(signo);

        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Clear text or whatever you want

                lblAnimacion.setVisible(false);
                Icon signo = new ImageIcon("igual.png");
                lblSigno.setIcon(signo);
            }
        });
        timer.start();  
    }
    
    // Envia la respuesta a la matriz de componentes
    public void diccionario_respuestas(int multiplicando, int multiplicador, int respuesta){
            for(int  fila=0; fila<filas; fila++){
            for(int columna=0; columna<columnas; columna++){
                   // botones[0][1].setForeground(Color.yellow); 
                    botones[multiplicando][multiplicador].setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                    botones[multiplicando][multiplicador].setHorizontalAlignment(SwingConstants.CENTER);
                        //botones[fila][columna].setBorder(border);
                    botones[multiplicando][multiplicador].setForeground(Color.blue);                    
                    botones[multiplicando][multiplicador].setX(String.valueOf(respuesta));        
            }}                  
                        
    }
    
    
    public void limpiar(){
        //lblMultiplicando.setText("");
        //lblMultiplicador.setText("");
        lblResultado.setText("");
    }
    
    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        lblResultado.setText(lblResultado.getText()+"7");
        check_enabled_boton();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        lblResultado.setText(lblResultado.getText()+"8");
        check_enabled_boton();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        lblResultado.setText(lblResultado.getText()+"9");
        check_enabled_boton();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        lblResultado.setText(lblResultado.getText()+"4");
        check_enabled_boton();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        lblResultado.setText(lblResultado.getText()+"5");
        check_enabled_boton();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        lblResultado.setText(lblResultado.getText()+"6");
       check_enabled_boton();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        lblResultado.setText(lblResultado.getText()+"1");
        check_enabled_boton();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        lblResultado.setText(lblResultado.getText()+"2");
        check_enabled_boton();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        lblResultado.setText(lblResultado.getText()+"3");
        check_enabled_boton();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        lblResultado.setText(lblResultado.getText()+"0");
        check_enabled_boton();
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        // TODO add your handling code here:
        String resultado = lblResultado.getText();
        System.out.println(resultado);
        int total = resultado.length();
        if (total > 0) {
            //System.out.println(total);
            String nuevo = resultado.substring(0, total - 1);
            //System.out.println(nuevo);
            lblResultado.setText(nuevo);
        } else {
            //System.out.println("escriba para poder borrar");
            check_disabled_boton();
        }   

    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
        this.hide();
        
        nivel2 niv2 = new nivel2(this.tiempo, this.sonido);
        niv2.getContentPane().setBackground(new Color(173, 202, 255));
        niv2.show();        
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new nivel2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton btnborrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelScore;
    private javax.swing.JLabel lblAnimacion;
    private javax.swing.JLabel lblMultiplicador;
    private javax.swing.JLabel lblMultiplicando;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSigno;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblsigno;
    // End of variables declaration//GEN-END:variables
}
