/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinaljuego;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author JDevp
 */
public class principal extends javax.swing.JFrame {

    boolean flag_sonido = true;
    boolean flag_tiempo = true;
    
    nivel1 niv1;
    nivel2 niv2;
    nivel3 niv3;
    
    /**
     * Creates new form principal
     */
    
    public principal() {
        initComponents();
        
        // Verificando si se completó el nivel
        verificar_niveles();
        
    
    }

    public void verificar_niveles(){
        
        if(niv1.getCounter() > 0 ){
            lblCompletado1.setText("Nivel Completado");
        } else {
            lblCompletado1.setText("");
        }

        if(niv2.getCounter() > 0 ){
            lblCompletado2.setText("Nivel Completado");
        } else {
            lblCompletado2.setText("");
        } 
        
        if(niv3.getCounter() > 0 ){
            lblCompletado3.setText("Nivel Completado");
        } else {
            lblCompletado3.setText("");
        }         
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNivel1 = new javax.swing.JButton();
        btnNivel2 = new javax.swing.JButton();
        btnNivel3 = new javax.swing.JButton();
        btnSonido = new javax.swing.JButton();
        btnTiempo = new javax.swing.JButton();
        lblCompletado1 = new javax.swing.JLabel();
        lblCompletado2 = new javax.swing.JLabel();
        lblCompletado3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Final");
        setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Multiply");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Escoge tu nivel");

        btnNivel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/nivel1.png"))); // NOI18N
        btnNivel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNivel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNivel1.setName(""); // NOI18N
        btnNivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivel1ActionPerformed(evt);
            }
        });

        btnNivel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/nivel2.png"))); // NOI18N
        btnNivel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNivel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNivel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivel2ActionPerformed(evt);
            }
        });

        btnNivel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/nivel3.png"))); // NOI18N
        btnNivel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNivel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNivel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivel3ActionPerformed(evt);
            }
        });

        btnSonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/sonido.png"))); // NOI18N
        btnSonido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSonido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSonido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonidoActionPerformed(evt);
            }
        });

        btnTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/reloj.png"))); // NOI18N
        btnTiempo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTiempo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiempoActionPerformed(evt);
            }
        });

        lblCompletado1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCompletado1.setText("jLabel3");

        lblCompletado2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCompletado2.setText("jLabel3");

        lblCompletado3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCompletado3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSonido, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236)
                        .addComponent(btnNivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                        .addComponent(btnNivel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(lblCompletado1)
                .addGap(437, 437, 437)
                .addComponent(lblCompletado2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCompletado3)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addGap(573, 573, 573)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompletado1)
                    .addComponent(lblCompletado2)
                    .addComponent(lblCompletado3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNivel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnSonido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivel1ActionPerformed
        // TODO add your handling code here:
        nivel1 niv1 = new nivel1(flag_tiempo,flag_sonido);
        this.hide();
        niv1.show();
        niv1.getContentPane().setBackground(new Color(173, 202, 255));
    }//GEN-LAST:event_btnNivel1ActionPerformed

    private void btnSonidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonidoActionPerformed
        // TODO add your handling code here:
        if (flag_sonido){
            Icon i=new ImageIcon("nosonido.png");
            btnSonido.setIcon(i);
            flag_sonido = false;
        } else {
            Icon i=new ImageIcon("sonido.png");
            btnSonido.setIcon(i);
            flag_sonido = true;
        }

    }//GEN-LAST:event_btnSonidoActionPerformed

    private void btnTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiempoActionPerformed
        // TODO add your handling code here:
        if (flag_tiempo){
            Icon i=new ImageIcon("notiempo.png");
            btnTiempo.setIcon(i);
            flag_tiempo = false;
            System.out.println(flag_tiempo);
        } else {
            Icon i=new ImageIcon("reloj.png");
            btnTiempo.setIcon(i);
            flag_tiempo = true;
            System.out.println(flag_tiempo);
        }        
    }//GEN-LAST:event_btnTiempoActionPerformed

    private void btnNivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivel2ActionPerformed
        // TODO add your handling code here:
        nivel2 niv2 = new nivel2(flag_tiempo,flag_sonido);
        //System.out.println("flag tiempo enviada: "+flag_tiempo);
        //niv2.tiempo = flag_tiempo;
        this.hide();
        niv2.show();
        niv2.getContentPane().setBackground(new Color(173, 202, 255));        
    }//GEN-LAST:event_btnNivel2ActionPerformed

    private void btnNivel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivel3ActionPerformed
        // TODO add your handling code here:
        nivel3 niv3 = new nivel3(flag_tiempo,flag_sonido);
        //System.out.println("flag tiempo enviada: "+flag_tiempo);
        //niv2.tiempo = flag_tiempo;
        this.hide();
        niv3.show();
        niv3.getContentPane().setBackground(new Color(173, 202, 255));         
    }//GEN-LAST:event_btnNivel3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNivel1;
    private javax.swing.JButton btnNivel2;
    private javax.swing.JButton btnNivel3;
    private javax.swing.JButton btnSonido;
    private javax.swing.JButton btnTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCompletado1;
    private javax.swing.JLabel lblCompletado2;
    private javax.swing.JLabel lblCompletado3;
    // End of variables declaration//GEN-END:variables
}
